language: python
python:
   - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python tests.py

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database user_manage;' -U postgres
  - python db.py db init
  - python db.py db migrate
  - python db.py db upgrade
  - python create_user.py
